#!/bin/bash
set -euo pipefail

if [ "$(id -u)" -eq 0 ]; then
    echo "spr-herdr sandbox must run as an unprivileged user" >&2
    exit 1
fi

home_dir=/home/herdr

if [ "$#" -eq 0 ]; then
    set -- /usr/local/bin/herdr
fi

runtime_dir="/run/user/$(id -u)"
seccomp_profile=/usr/share/spr-herdr/vsock-seccomp.bpf
terminal_type="${TERM:-xterm-256color}"
color_terminal="${COLORTERM:-truecolor}"
exec 3<"$seccomp_profile"
unset SPR_KRUN_PLUGIN_SOCKET SPR_KRUN_VSOCK_PORT

exec -c /usr/bin/bwrap \
    --die-with-parent \
    --new-session \
    --unshare-user \
    --uid "$(id -u)" \
    --gid "$(id -g)" \
    --unshare-pid \
    --unshare-ipc \
    --unshare-uts \
    --ro-bind /usr /usr \
    --symlink usr/bin /bin \
    --symlink usr/sbin /sbin \
    --symlink usr/lib /lib \
    --symlink usr/lib64 /lib64 \
    --dir /etc \
    --ro-bind /etc/alternatives /etc/alternatives \
    --ro-bind /etc/bash.bashrc /etc/bash.bashrc \
    --ro-bind /etc/ca-certificates.conf /etc/ca-certificates.conf \
    --ro-bind /etc/group /etc/group \
    --ro-bind /etc/host.conf /etc/host.conf \
    --ro-bind /etc/hostname /etc/hostname \
    --ro-bind /etc/hosts /etc/hosts \
    --ro-bind /etc/ld.so.cache /etc/ld.so.cache \
    --ro-bind /etc/ld.so.conf /etc/ld.so.conf \
    --ro-bind /etc/ld.so.conf.d /etc/ld.so.conf.d \
    --ro-bind /etc/nsswitch.conf /etc/nsswitch.conf \
    --ro-bind /etc/passwd /etc/passwd \
    --ro-bind /etc/profile /etc/profile \
    --ro-bind /etc/profile.d /etc/profile.d \
    --ro-bind /etc/resolv.conf /etc/resolv.conf \
    --ro-bind /etc/shells /etc/shells \
    --ro-bind /etc/ssh /etc/ssh \
    --ro-bind /etc/ssl /etc/ssl \
    --ro-bind /etc/timezone /etc/timezone \
    --ro-bind-try /etc/environment /etc/environment \
    --ro-bind-try /etc/gai.conf /etc/gai.conf \
    --ro-bind-try /etc/gitconfig /etc/gitconfig \
    --ro-bind-try /etc/inputrc /etc/inputrc \
    --ro-bind-try /etc/nanorc /etc/nanorc \
    --ro-bind-try /etc/networks /etc/networks \
    --ro-bind-try /etc/protocols /etc/protocols \
    --ro-bind-try /etc/services /etc/services \
    --ro-bind-try /etc/vim /etc/vim \
    --symlink ../usr/lib/os-release /etc/os-release \
    --symlink /proc/mounts /etc/mtab \
    --symlink ../usr/share/zoneinfo/Etc/UTC /etc/localtime \
    --dir /home \
    --bind "$home_dir" "$home_dir" \
    --tmpfs /run \
    --perms 0700 \
    --dir "$runtime_dir" \
    --perms 0755 \
    --dir /run/lock \
    --perms 1777 \
    --tmpfs /tmp \
    --dir /var \
    --perms 1777 \
    --dir /var/tmp \
    --symlink /run /var/run \
    --symlink /run/lock /var/lock \
    --proc /proc \
    --dev /dev \
    --chdir /home/herdr/workspace \
    --clearenv \
    --setenv HOME "$home_dir" \
    --setenv USER herdr \
    --setenv LOGNAME herdr \
    --setenv SHELL /bin/bash \
    --setenv PATH /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    --setenv TERM "$terminal_type" \
    --setenv COLORTERM "$color_terminal" \
    --setenv LANG C.UTF-8 \
    --setenv PWD /home/herdr/workspace \
    --setenv XDG_CONFIG_HOME /home/herdr/.config \
    --setenv XDG_CACHE_HOME /home/herdr/.cache \
    --setenv XDG_DATA_HOME /home/herdr/.local/share \
    --setenv XDG_RUNTIME_DIR "$runtime_dir" \
    --setenv HERDR_CONFIG_PATH /home/herdr/.config/herdr/config.toml \
    --setenv HERDR_DISABLE_SOUND 1 \
    --seccomp 3 \
    --cap-drop ALL \
    -- \
    "$@"
